# Generated by Django 3.2 on 2025-03-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Элетронная почта пользователя', max_length=254, null=True, unique=True, verbose_name='Электронная почта'),
        ),
    ]
