# Generated by Django 3.2 on 2025-03-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, help_text='Элетронная почта пользователя', max_length=254, unique=True, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
    ]
